#!/usr/bin/env node --trace-deopt --trace-deprecation
'use strict';

const f2 = require('../bundle');

const data2 = {who: 'Polly', what: 'cracker'};
const data3 = {data: data2};

function sample(f2, data2, data3) {
    f2.subst('Polly wants %s %d', data2.what, 2);
    f2.subst('Polly wants %(what)s', data2);
    f2.subst('%s wants %(what)s', data2.who, data2);
    f2.subst('%(who)s wants %(what)s', data2);
    f2.subst('%(who)j wants %(what)s', data2);
    f2.subst('%(.data.who)s wants %(.data.what)s', 'and jam', data3);
}

for (let i = 0, l = 1000000; i < l; i = i + 1) {
    sample(f2, data2, data3);
}
