#!/usr/bin/env node --trace-deopt
'use strict';

var f2 = require('../');
var l = 10000000;

while (l > 0) {
    l -= 1;
    f2.format('Polly wants %s', 'cracker');
    f2.format('Polly wants %(what)s', {what: 'cracker'});
    f2.format('%s wants %(what)s', 'Polly', {what: 'cracker'});
    f2.format('%(who)s wants %(what)s', {who: 'Polly', what: 'cracker'});
    f2.format('%(.data.who)s wants %(.data.what)s', {data: {who: 'Polly', what: 'cracker'}});
}
